server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /web

spring:
  application:
    name: fast-web
  # 环境 dev
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    # 开启全局异常捕获NoHandlerFoundException异常
    throw-exception-if-no-handler-found: true
    # 避免无法捕获NoHandlerFoundException，如果地址错误SpringMvc优先被默认的/**静态资源映射当成静态资源处理
    static-path-pattern: /static/**
  main:
    # 开启Bean覆盖
    allow-bean-definition-overriding: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  typeAliasesPackage: com.lv.**.DO
  global-config:
    #数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
    # 是否开启控制台 print mybatis-plus 的 LOGO
    banner: false
  #原生配置
  configuration:
    #开启数据库_与实体驼峰映射
    map-underscore-to-camel-case: true
    # 禁用缓存
    cache-enabled: false
    # 如果查询字段为null返回key
    call-setters-on-nulls: true
    # 允许value为null
    jdbc-type-for-null: 'null'

#Actuator配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health'
      base-path: /info