server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /web

spring:
  application:
    name: fast-web
  # 环境 dev
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    # 开启全局异常捕获NoHandlerFoundException异常
    throw-exception-if-no-handler-found: true
    # 避免无法捕获NoHandlerFoundException，如果地址错误SpringMvc优先被默认的/**静态资源映射当成静态资源处理
    static-path-pattern: /static/**
  main:
    # 开启Bean覆盖
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      #最大连接数 默认值：10 建议不要配置最小连接数minimumIdle  让HikariCP充当固定大小的连接池
      maximumPoolSize: 15
      #建议不要配置最小连接数minimumIdle 默认值与maximumPoolSize相同  让HikariCP充当固定大小的连接池,防止空闲很久时创建连接耗时较长从而影响RT
      #minimum-idle: 15
      #连接在池中空闲的最长时间  默认值：600000（10分钟） 当且仅当minimumIdle小于maximumPoolSize 时才会生效
      #idleTimeout: 30000
      #是否开启自动提交  默认为true
      auto-commit: true
      #连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中，以识别池和池配置。 默认值：自动生成
      poolName: DatebookHikariCP
      #连接的最大生存期 最小允许值为30000ms（30秒）。 默认值：1800000（30分钟） 单位毫秒
      maxLifetime: 1800000
      #最大连接超时时间  默认30秒  单位毫秒
      connectionTimeout: 30000

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  typeAliasesPackage: com.**.DO
  global-config:
    #数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
    # 是否开启控制台 print mybatis-plus 的 LOGO
    banner: false
  #原生配置
  configuration:
    #开启数据库_与实体驼峰映射
    map-underscore-to-camel-case: true
    # 禁用缓存
    cache-enabled: false
    # 如果查询字段为null返回key
    call-setters-on-nulls: true
    # 允许value为null
    jdbc-type-for-null: 'null'
  # 配置枚举扫描包
  type-enums-package: com.**.enums

#Actuator配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health'
      base-path: /info

# xss攻击配置 参考文档https://www.dreamlu.net/components/mica-xss.html
mica:
  xss:
    # 是否开启Xss
    enabled: true
    # 是否去掉前后空格
    trim-text: true
    # 模式：clear 清理（默认），escape 转义
    mode: escape
    # 拦截路径
    path-patterns: ${server.servlet.context-path}