spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      password:
      database: 0
      host: 127.0.0.1
      timeout: 1000ms
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-active: 15
          min-idle: 0
          max-idle: 50

#mybatis-plus日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置日志
logging:
  level:
    root: debug

# spring doc配置
springdoc:
  # 开启swagger
  swagger-ui:
    enabled: true