spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#mybatis-plus日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  #是否生产环境  生产环境会关闭访问
  production: false
  basic:
    #是否开启认证
    enable: true
    #认证用户名
    username: admin
    #认证密码
    password: admin

#配置日志
logging:
  level:
    root: debug

# 自定义配置
my:
  jwt:
    # 加密密钥
    secret: fast@jwt#token$2021
    # 有效期限 单位s 默认24小时
    validDuration: 86400